blog/blog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('myblog.urls', namespace='myblog')),
    path('', include('users.urls', namespace='users')),
]

blog/myblog/urls.py
from django.urls import path
from . import views

app_name = 'myblog'

urlpatterns = [
    path('', views.index, name='index'),
    path('posts/', views.posts, name='posts'),
]

blog/users/urls.py
from django.urls import path
from users.views import register_user, login_user, logout_user

app_name = 'users'

urlpatterns = [
    path('register/', register_user, name='register_user'),
    path('login/', login_user, name='login_user'),
    path('logout/', logout_user, name='logout_user'),
]

blog/myblog/models.py
from django.db import models
from users.models import User


class Post(models.Model):
    title = models.CharField(max_length=100, null=False, blank=False)
    description = models.TextField(max_length=5000, null=False, blank=False)
    create_by = models.DateField(auto_now_add=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE, null=False, blank=False)

    def __str__(self):
        return f'{self.title} | {self.author}'

blog/users/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser
from django.contrib.auth.base_user import BaseUserManager


class UserManager(BaseUserManager):
    """
    В коде, UserManager не используется напрямую, но он указан в классе User как objects.
    Это означает, что UserManager используется для управления объектами класса User в Django.
    Он тут не ипользуется на прямую, но отвечает за удаление, добовление объектов класса User
    """
    # Указание что этот менджер должен быть использован в миграциях джанго
    use_in_migrations = True

    # Создание пользователя и вывод исключения в терминал
    def create_user(self, email, password, **extra_fields):
        if not email:
            raise ValueError('У пользователя должен быть email')
        email = self.normalize_email(email)  # Нормализует данные, переводит в нижний регистор, удаляет пробелы и т.д
        user = self.model(email=email, **extra_fields)  # Ссылка на модель, передача email и других полей (extra_fields)
        user.set_password(password)  # Устонавливает пароль
        user.save(using=self._db)  # Сохроняет пользователя в бд
        return user

    # Создание супер пользователя
    def create_superuser(self, email, password, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)
        extra_fields.setdefault('is_active', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')

        return self.create_user(email, password, **extra_fields)


class User(AbstractBaseUser):
    email = models.EmailField(unique=True, null=False, blank=False)
    username = models.CharField(max_length=40, unique=True, null=False, blank=False)
    first_name = models.CharField(max_length=60, null=False, blank=False)
    last_name = models.CharField(max_length=60, null=False, blank=False)
    is_active = models.BooleanField(default=True)
    is_admin = models.BooleanField(default=False)
    is_staff = models.BooleanField(default=False)
    is_superuser = models.BooleanField(default=False)

    objects = UserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username']

    def has_perm(self, perm, obj=None):
        return self.is_superuser

    def has_module_perms(self, app_label):
        return self.is_superuser

    def __str__(self):
        return self.username

    class Meta:
        verbose_name = 'Authorized user'
        verbose_name_plural = 'Authorized users'

blog/users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm, AuthenticationForm

from users.models import User


class UserRegistrationForm(forms.ModelForm):
    email = forms.EmailField(widget=forms.EmailInput(attrs={'class': 'register__fields__email', 'placeholder': 'Email'}))
    username = forms.CharField(widget=forms.TextInput(attrs={'class': 'register__fields__username', 'placeholder': 'Username'}))
    first_name = forms.CharField(widget=forms.TextInput(attrs={'class': 'register__fields__firstname', 'placeholder': 'First name'}))
    last_name = forms.CharField(widget=forms.TextInput(attrs={'class': 'register__fields__lastname', 'placeholder': 'Last name'}))
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'register__fields__password', 'placeholder': 'Password'}))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'register__fields__repairpassword', 'placeholder': 'Repair password'}))

    class Meta:
        model = User
        fields = ('email', 'username', 'first_name', 'last_name', 'password1', 'password2', )


class UserLoginForm(forms.Form):
    username = forms.CharField(
        widget=forms.TextInput(attrs={
            'class': 'login__fields__username', 'placeholder': 'Username'
        }))
    password = forms.CharField(
        widget=forms.PasswordInput(attrs={
            'class': 'login__fields__password', 'placeholder': 'Password'
        }))

    class Meta:
        model = User
        fields = ('username', 'password', )

blog/myblog/views.py
from django.shortcuts import render
from users.models import User


def index(request):
    context = {
        'title': 'blog',
        'users': User.objects.all(),
    }
    return render(request, 'myblog/home.html', context)


def posts(request):
    context = {
        'title': 'SLVNV - All posts',
    }
    return render(request, 'myblog/posts.html', context)

blog/users/views.py
from django.shortcuts import render
from django.urls import reverse
from django.contrib.auth import authenticate, login, logout
from django.contrib import auth
from users.models import User
from django.http import HttpResponseRedirect
from users.forms import UserRegistrationForm, UserLoginForm


def register_user(request):
    if request.method == 'POST':
        form = UserRegistrationForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)  # Не сохраняется в бд
            user.set_password(form.cleaned_data['password1'])
            user.save()
            return HttpResponseRedirect(reverse('users:login_user'))
    else:
        form = UserRegistrationForm()
    context = {
        'form': form,
        'title': 'Register in website'
    }
    return render(request, 'users/register.html', context)


def login_user(request):
    if request.method == 'POST':
        form = UserLoginForm(request.POST)
        if form.is_valid():
            username = request.POST['username']
            password = request.POST['password']
            user = auth.authenticate(request, username=username, password=password)
            if user is not None:
                auth.login(request, user)
                return HttpResponseRedirect(reverse('myblog:index'))
        else:
            return render(request, 'users/login.html', {'form': form})
    else:
        form = UserLoginForm()
    return render(request, 'users/login.html', {'form': form})


def logout_user(request):
    logout(request)
    return HttpResponseRedirect(reverse('myblog:index'))

blog/myblog/templates/myblog/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>SLVNV website</title>
    <link rel="stylesheet" href="{% static 'myblog/css/style.css' %}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/locomotive-scroll@3.5.4/dist/locomotive-scroll.css">
</head>
<body>
    <div id="main">
    {% include 'myblog/complex/_navbar.html' %}
        {% block content %}

        {% endblock content %}

        <div class="footer__home">
            <div class="container">
                <div class="left__text"><a href="#">GitHub this website link</a></div>
                <div class="right__text">Programming and deisgn create by Yaroslav Selivanov</div>
            </div>
        </div>

        <script src="https://cdn.jsdelivr.net/npm/locomotive-scroll@3.5.4/dist/locomotive-scroll.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/gsap/3.12.2/ScrollTrigger.min.js"
            integrity="sha512-Ic9xkERjyZ1xgJ5svx3y0u3xrvfT/uPkV99LBwe68xjy/mGtO+4eURHZBW2xW4SZbFrF1Tf090XqB+EVgXnVjw=="
            crossorigin="anonymous" referrerpolicy="no-referrer"></script>
        <script src="{% static 'myblog/js/script.js' %}"></script>
    </div>
</body>
</html>

blog/myblog/templates/myblog/complex/_navbar.html
<div class="header">
    <div class="container">
        <div class="header__logo" style="cursor: default;">
            <h3>slvnv</h3>
        </div>
        <div class="header__menu">
            <a href="{% url 'myblog:index' %}">Home</a>
            <a href="{% url 'myblog:posts' %}">Posts</a>
            <a href="#">Music</a>
            <a href="#">About me</a>
        </div>
        <div class="header__search">
            <input type="text" placeholder="Search" class="search-input">
        </div>
        {% if user.is_authenticated %}
            <div class="header__buttons">
                <div class="header__buttons__signin">
                    <a href="{% url 'users:logout_user' %}"><button>Logout</button></a>
                </div>
            </div>
        {% else %}
            <div class="header__buttons">
            <div class="header__buttons__signin">
                <a href="{% url 'users:login_user' %}"><button>Sign in</button></a>
            </div>
            <div class="header__buttons__signup">
                <a href="{% url 'users:register_user' %}"><button>Sign up</button></a>
            </div>
        </div>
        {% endif %}
    </div>
</div>

blog/myblog/templates/myblog/home.html
{% extends 'myblog/base.html' %}
{% load static %}

{% block content %}
    <div class="main">
            <div class="container">
                {% if user.is_authenticated %}
                <h1>HELLO USER! {{ user.username }}</h1>
                    {% else %}
                    <h1>NO authenticated</h1>
                {% endif %}
                <div class="main__title__info">
                    <h1>Hello user, I’m Yaroslav.</h1>
                    <p>I am a developer and I am trying to improve my skills by developing various websites, systems and web applications. This blog is my project to practice my skills. On this site you can read existing posts or add your own</p>
                </div>
                <div class="more__posts">
                    <div class="more__post__title">
                        <h2>Сurrent posts for today</h2>
                    </div>
                    <div class="wrapper">
                        <div class="posts">
                            <a href="#">
                                <div class="post">
                                    <div class="post__title">
                                        The post title
                                    </div>
                                    <div class="post__subtitle">
                                        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut egestas risus non turpis sollicitudin placerat. Phasellus tincidunt risus quis mi convallis, quis luctus ex fringilla. Sed ac ex nisi
                                    </div>
                                    <div class="more_info">
                                        <div class="post__date">
                                            01.01.1001
                                        </div>
                                        <div class="post__author">
                                            Yaroslav
                                        </div>
                                    </div>
                                </div>
                            </a>

                            <a href="#">
                                <div class="post">
                                    <div class="post__title">
                                        The post title
                                    </div>
                                    <div class="post__subtitle">
                                        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut egestas risus non turpis sollicitudin placerat. Phasellus tincidunt risus quis mi convallis, quis luctus ex fringilla. Sed ac ex nisi
                                    </div>
                                    <div class="more_info">
                                        <div class="post__date">
                                            01.01.1001
                                        </div>
                                        <div class="post__author">
                                            Yaroslav
                                        </div>
                                    </div>
                                </div>
                            </a>

                            <a href="#">
                                <div class="post">
                                    <div class="post__title">
                                        The post title
                                    </div>
                                    <div class="post__subtitle">
                                        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut egestas risus non turpis sollicitudin placerat. Phasellus tincidunt risus quis mi convallis, quis luctus ex fringilla. Sed ac ex nisi
                                    </div>
                                    <div class="more_info">
                                        <div class="post__date">
                                            01.01.1001
                                        </div>
                                        <div class="post__author">
                                            Yaroslav
                                        </div>
                                    </div>
                                </div>
                            </a>

                            <a href="#">
                                <div class="post">
                                    <div class="post__title">
                                        The post title
                                    </div>
                                    <div class="post__subtitle">
                                        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut egestas risus non turpis sollicitudin placerat. Phasellus tincidunt risus quis mi convallis, quis luctus ex fringilla. Sed ac ex nisi
                                    </div>
                                    <div class="more_info">
                                        <div class="post__date">
                                            01.01.1001
                                        </div>
                                        <div class="post__author">
                                            Yaroslav
                                        </div>
                                    </div>
                                </div>
                            </a>

                            <a href="#">
                                <div class="post">
                                    <div class="post__title">
                                        The post title
                                    </div>
                                    <div class="post__subtitle">
                                        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut egestas risus non turpis sollicitudin placerat. Phasellus tincidunt risus quis mi convallis, quis luctus ex fringilla. Sed ac ex nisi
                                    </div>
                                    <div class="more_info">
                                        <div class="post__date">
                                            01.01.1001
                                        </div>
                                        <div class="post__author">
                                            Yaroslav
                                        </div>
                                    </div>
                                </div>
                            </a>

                            <a href="#">
                                <div class="post">
                                    <div class="post__title">
                                        The post title
                                    </div>
                                    <div class="post__subtitle">
                                        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut egestas risus non turpis sollicitudin placerat. Phasellus tincidunt risus quis mi convallis, quis luctus ex fringilla. Sed ac ex nisi
                                    </div>
                                    <div class="more_info">
                                        <div class="post__date">
                                            01.01.1001
                                        </div>
                                        <div class="post__author">
                                            Yaroslav
                                        </div>
                                    </div>
                                </div>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
    </div>
{% endblock content %}

blog/users/templates/users/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="{% static 'users/css/style.css' %}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/locomotive-scroll@3.5.4/dist/locomotive-scroll.css">
</head>
<body>
    {% block content %}

    {% endblock content %}
</body>
</html>

blog/users/templates/users/login.html
{% extends 'users/base.html' %}
{% load static %}
<title>Login</title>
{% block content %}
    {% include 'myblog/complex/_navbar.html' %}
    <div class="container">
        <form action="{% url 'users:login_user' %}" method="post">
            {% csrf_token %}
            {% if form.non_field_errors %}
                <p>{{ form.non_field_errors }}</p>
            {% endif %}

            <!-- Rest of your form -->
            <div class="login">
                    <div class="login__title">Login for <br>this website</div>
                    <div class="login__subtitle">If you already have an account, simply log in by entering your details.</div>
                    <div class="login__fields">
                        <div class="login__fields__username">
                            {{ form.username }}
                        </div>
                        <div class="login__fields__password">
                            {{ form.password }}
                        </div>
                    </div>
                    <div class="login__buttons">
                        <button class="login__btn" type="submit">Login in account</button>
                        <p class="linktext">You don't have account? <a href="{% url 'users:register_user' %}" class="linktext">Register</a></p>
                    </div>
            </div>
        </form>
    </div>
{% endblock content %}

blog/users/templates/users/register.html
{% extends 'users/base.html' %}
{% load static %}
<title>{{ title }}</title>
{% block content %}
    {% include 'myblog/complex/_navbar.html' %}
    <div class="container">
        <form action="" method="post">
            {% csrf_token %}
            <div class="register">
                    <div class="register__title">Register for <br>this website</div>
                    <div class="register__subtitle">If this is your first time on the site, register your account to continue.</div>
{#                    {{ form.as_p }}#}
                    {% if form.errors %}
                        <ul>
                            {% for field in form %}
                                {% if field.errors %}
                                    <li>{{ field.label }}: {{ field.errors|join:", " }}</li>
                                {% endif %}
                            {% endfor %}
                        </ul>
                    {% endif %}
                    <div class="register__fields">
                            <div class="register__fields__email">
                                {{ form.email }}
                            </div>
                            <div class="register__fields__username">
                                {{ form.username }}
                            </div>

                            <div class="firstname_and_lastname">
                                <div class="register__fields__firstname">
                                    {{ form.first_name }}
                                </div>
                                <div class="register__fields__lastname">
                                    {{ form.last_name }}
                                </div>
                            </div>

                            <div class="register__fields__password">
                                {{ form.password1 }}
                            </div>
                            <div class="register__fields__repairpassword">
                                {{ form.password2 }}
                            </div>
                        </div>
                    <div class="register__buttons">
                        <button class="register__btn" type="submit">Register account</button>
                        <p class="linktext">You have account? <a href="#" class="linktext">Login</a></p>
                    </div>
                </div>
        </form>
    </div>
</form>
{% endblock content %}

templates/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>SLVNV website</title>
    <link rel="stylesheet" href="static/css/style.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/locomotive-scroll@3.5.4/dist/locomotive-scroll.css">
</head>
<body>
    <div id="main">
        <div class="header">
            <div class="container">
                <div class="header__logo" style="cursor: default;">
                    <h3>slvnv</h3>
                </div>
                <div class="header__menu">
                    <a href="home.html">Home</a>
                    <a href="posts.html">Posts</a>
                    <a href="music.html">Music</a>
                    <a href="about.html">About me</a>
                </div>
                <div class="header__search">
                    <input type="text" placeholder="Search" class="search-input">
                </div>
                <div class="header__buttons">
                    <div class="header__buttons__signin">
                        <a href="#"><button>Sign in</button></a>
                    </div>
                    <div class="header__buttons__signup">
                        <a href="#"><button>Sign up</button></a>
                    </div>
                </div>
            </div>
        </div>
        <div class="main">
            <div class="container">
                <div class="main__title__info">
                    <h1>Hello user, I’m Yaroslav.</h1>
                    <p>I am a developer and I am trying to improve my skills by developing various websites, systems and web applications. This blog is my project to practice my skills. On this site you can read existing posts or add your own</p>
                </div>
                <div class="more__posts">
                    <div class="more__post__title">
                        <h2>Сurrent posts for today</h2>
                    </div>
                    <div class="wrapper">
                        <div class="posts">
                            <a href="#">
                                <div class="post">
                                    <div class="post__title">
                                        The post title
                                    </div>
                                    <div class="post__subtitle">
                                        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut egestas risus non turpis sollicitudin placerat. Phasellus tincidunt risus quis mi convallis, quis luctus ex fringilla. Sed ac ex nisi
                                    </div>
                                    <div class="more_info">
                                        <div class="post__date">
                                            01.01.1001
                                        </div>
                                        <div class="post__author">
                                            Yaroslav
                                        </div>
                                    </div>
                                </div>
                            </a>
        
                            <a href="#">
                                <div class="post">
                                    <div class="post__title">
                                        The post title
                                    </div>
                                    <div class="post__subtitle">
                                        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut egestas risus non turpis sollicitudin placerat. Phasellus tincidunt risus quis mi convallis, quis luctus ex fringilla. Sed ac ex nisi
                                    </div>
                                    <div class="more_info">
                                        <div class="post__date">
                                            01.01.1001
                                        </div>
                                        <div class="post__author">
                                            Yaroslav
                                        </div>
                                    </div>
                                </div>
                            </a>
        
                            <a href="#">
                                <div class="post">
                                    <div class="post__title">
                                        The post title
                                    </div>
                                    <div class="post__subtitle">
                                        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut egestas risus non turpis sollicitudin placerat. Phasellus tincidunt risus quis mi convallis, quis luctus ex fringilla. Sed ac ex nisi
                                    </div>
                                    <div class="more_info">
                                        <div class="post__date">
                                            01.01.1001
                                        </div>
                                        <div class="post__author">
                                            Yaroslav
                                        </div>
                                    </div>
                                </div>
                            </a>
    
                            <a href="#">
                                <div class="post">
                                    <div class="post__title">
                                        The post title
                                    </div>
                                    <div class="post__subtitle">
                                        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut egestas risus non turpis sollicitudin placerat. Phasellus tincidunt risus quis mi convallis, quis luctus ex fringilla. Sed ac ex nisi
                                    </div>
                                    <div class="more_info">
                                        <div class="post__date">
                                            01.01.1001
                                        </div>
                                        <div class="post__author">
                                            Yaroslav
                                        </div>
                                    </div>
                                </div>
                            </a>
        
                            <a href="#">
                                <div class="post">
                                    <div class="post__title">
                                        The post title
                                    </div>
                                    <div class="post__subtitle">
                                        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut egestas risus non turpis sollicitudin placerat. Phasellus tincidunt risus quis mi convallis, quis luctus ex fringilla. Sed ac ex nisi
                                    </div>
                                    <div class="more_info">
                                        <div class="post__date">
                                            01.01.1001
                                        </div>
                                        <div class="post__author">
                                            Yaroslav
                                        </div>
                                    </div>
                                </div>
                            </a>
        
                            <a href="#">
                                <div class="post">
                                    <div class="post__title">
                                        The post title
                                    </div>
                                    <div class="post__subtitle">
                                        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut egestas risus non turpis sollicitudin placerat. Phasellus tincidunt risus quis mi convallis, quis luctus ex fringilla. Sed ac ex nisi
                                    </div>
                                    <div class="more_info">
                                        <div class="post__date">
                                            01.01.1001
                                        </div>
                                        <div class="post__author">
                                            Yaroslav
                                        </div>
                                    </div>
                                </div>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="footer__home">
            <div class="container">
                <div class="left__text"><a href="#">GitHub this website link</a></div>
                <div class="right__text">Programming and deisgn create by Yaroslav Selivanov</div>
            </div>
        </div>
    
        <script src="https://cdn.jsdelivr.net/npm/locomotive-scroll@3.5.4/dist/locomotive-scroll.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/gsap/3.12.2/ScrollTrigger.min.js"
            integrity="sha512-Ic9xkERjyZ1xgJ5svx3y0u3xrvfT/uPkV99LBwe68xjy/mGtO+4eURHZBW2xW4SZbFrF1Tf090XqB+EVgXnVjw=="
            crossorigin="anonymous" referrerpolicy="no-referrer"></script>
        <script src="static/js/script.js"></script>
    </div>
</body>
</html>